#ifndef TEXTURES_H
#define TEXTURES_H

#include "color.h"


int TEXTURE_BRICK[] = {
    BLACK, RAINBOW, RAINBOW, RAINBOW, BLACK, RAINBOW, RAINBOW, RAINBOW,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    RAINBOW, RAINBOW, BLACK, RAINBOW, RAINBOW, RAINBOW, BLACK, RAINBOW,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, RAINBOW, RAINBOW, RAINBOW, BLACK, RAINBOW, RAINBOW, RAINBOW,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    RAINBOW, RAINBOW, BLACK, RAINBOW, RAINBOW, RAINBOW, BLACK, RAINBOW,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK
};

int getColor(int type) {
    switch (type)
    {
        case RAINBOW:
            return rainbow(4);
            break;
    }
    return type;
}
#endif